import { Router } from "express";
import stripeRoutes from "./stripe.routes";
import clerkRoutes from "./clerk.routes";
import userRoutes from "./user.routes";
import videoRoutes from "./video.routes";
import subtitleRoutes from "./subtitle.routes";
import exportRoutes from "./export.routes";
import connectRoutes from "./connect.routes";
import postRoutes from "./post.routes";
import scheduleRoutes from "./schedule.routes";
import libraryRoutes from "./library.routes";
import generationRoutes from "./generation.routes";
import imageGenerationRoutes from "./image-generations.routes";
import imageUpscalerRoutes from "./image-upscaler.routes";
import klingRoutes from "./kling.routes";
import videoUpscalerRoutes from "./video-upscaler.routes";
import motionControlRoutes from "./motion-control.routes";
import movieMaterialsRoutes from "./movie-materials.routes";
import influencerStudioRoutes from "./influencer-studio.routes";
import videoGenerationRoutes from "./video-generation.routes";
import assetRoutes from "./asset.routes";
import webhookRoutes from "./webhook.routes";
import clippingRoutes from "./clipping.routes";
import thumbnailsRoutes from "./thumbnails.routes";
import musicGenerationsRoutes from "./music-generations.routes";
import avatarGenerationsRoutes from "./avatar-generations.routes";
import voiceGenerationsRoutes from "./voice-generations.routes";
import voiceClonesRoutes from "./voice-clones.routes";
import voiceConversionsRoutes from "./voice-conversions.routes";
import uploadRoutes from "./upload.routes";
import skillsRoutes from "./skills.routes";
import adminRoutes from "./admin";

const router = Router();

router.use("/stripe", stripeRoutes);
router.use("/clerk", clerkRoutes);
router.use("/user", userRoutes);
router.use("/videos", videoRoutes);
router.use("/subtitles", subtitleRoutes);
router.use("/exports", exportRoutes);
router.use("/connect", connectRoutes);
router.use("/posts", postRoutes);
router.use("/schedule", scheduleRoutes);
router.use("/library", libraryRoutes);
router.use("/generations", generationRoutes);
router.use("/image-generations", imageGenerationRoutes);
router.use("/image-upscaler", imageUpscalerRoutes);
router.use("/kling", klingRoutes);
router.use("/video-upscaler", videoUpscalerRoutes);
router.use("/motion-control", motionControlRoutes);
router.use("/movie-materials", movieMaterialsRoutes);
router.use("/influencer-studio", influencerStudioRoutes);
router.use("/video-generation", videoGenerationRoutes);
router.use("/assets", assetRoutes);
router.use("/clippings", clippingRoutes);
router.use("/thumbnails", thumbnailsRoutes);
router.use("/music-generations", musicGenerationsRoutes);
router.use("/avatar-generations", avatarGenerationsRoutes);
router.use("/voice-generations", voiceGenerationsRoutes);
router.use("/voice-clones", voiceClonesRoutes);
router.use("/voice-conversions", voiceConversionsRoutes);
router.use("/uploads", uploadRoutes);
router.use("/skills", skillsRoutes);
router.use("/admin", adminRoutes);
router.use("/webhooks", webhookRoutes);

export default router;
